services:
    laravel.test:
        build:
            context: './docker/runtimes/8.4'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
                ACCEPT_EULA: '${ACCEPT_EULA}' # Accept the EULA to compile
        image: 'sail-8.4/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mssql
            - redis
            - meilisearch
            - mailpit
            - selenium
    mssql:
        image: 'mcr.microsoft.com/mssql/server:2022-latest'
        ports:
            - '${FORWARD_DB_PORT:-1433}:1433'
        environment:
            MSSQL_SA_PASSWORD: '${DB_ROOT_PASSWORD}'
            MSSQL_DB_NAME: '${DB_DATABASE}'
            MSSQL_USER: '${DB_USERNAME}'
            MSSQL_PASSWORD: '${DB_PASSWORD}'
            ACCEPT_EULA: '${ACCEPT_EULA}'
        volumes:
            - 'sail-mssql:/var/opt/mssql'
            - '.devcontainer/mssql_entrypoint.sh:/mssql_entrypoint.sh'
        networks:
            - sail
        entrypoint: '/mssql_entrypoint.sh'
        healthcheck:
            test: ["CMD", "sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${DB_PASSWORD}", "-Q", "SELECT 1"]
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        environment:
            MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
        volumes:
            - 'sail-meilisearch:/meili_data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - wget
                - '--no-verbose'
                - '--spider'
                - 'http://127.0.0.1:7700/health'
            retries: 3
            timeout: 5s
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
    selenium:
        image: selenium/standalone-chromium
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - '/dev/shm:/dev/shm'
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mssql:
        driver: local
    sail-redis:
        driver: local
    sail-meilisearch:
        driver: local
